apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoughts
  namespace: thoughts-system

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
      - name: thoughts-api
        resources:
          requests:
            cpu: "500m" 
          limits:
            cpu: "500m" 