apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/thoughts/
patches:
- path: ./dev-thoughts-patch-deploy.yaml
images:
- name: service-image
  newName: youngjun827/service/thoughts-api
  newTag: 0.0.1
