name: Run staticcheck
runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: '1.21.3'
  - name: Install staticcheck
    run: go install honnef.co/go/tools/cmd/staticcheck@latest
  - name: Run staticcheck
    run: staticcheck -checks=all ./...
