name: Run vet
runs-on: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: '1.21.3'
  - name: Run vet
    run: go vet ./...
