apiVersion: v1
kind: Namespace
metadata:
  name: thoughts-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoughts
  namespace: thoughts-system

spec:
  selector:
    matchLabels:
      app: thoughts

  template:
    metadata:
      labels:
        app: thoughts

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: thoughts-api
        image: service-image

      
        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu