apiVersion: v1
kind: Namespace
metadata:
  name: thoughts-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoughts
  namespace: thoughts-system

spec:
  selector:
    matchLabels:
      app: thoughts

  template:
    metadata:
      labels:
        app: thoughts

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: thoughts-api
        image: service-image

        ports:
        - name: thoughts-api
          containerPort: 3000 
        - name: thts-api-debug # Stands for thoughts-api-debug. Truncated due to K8s port name character limit.
          containerPort: 4000
        
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /v1/readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /v1/liveness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: thoughts-api
  namespace: thoughts-system
  
spec:
  selector:
    app: thoughts