name: Build

on: [push, pull_request]

jobs:
  test:
    uses: ./jobs/test.yml

  vet:
    uses: ./jobs/vet.yml

  staticcheck:
    uses: ./jobs/staticcheck.yml

  govulncheck:
    uses: ./jobs/govulncheck.yml
