name: Build and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Format code
        run: |
          gofmt -s -w .
          
      - name: Install golint
        run: |
          go install golang.org/x/lint/golint
          
      - name: Lint code
        run: |
          golint ./...
          
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          
      - name: Run golangci-lint
        run: |
          golangci-lint run

      - name: Run tests
        run: |
          go test ./...

      - name: Run vet
        run: |
          go vet ./...

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: |
          staticcheck -checks=all ./...

      - name: Install govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: |
          govulncheck ./...
