name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "Logged in to Docker Hub"

      - name: Push Docker Images to Docker Hub
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t thoughts/thoughts-api:latest -f operations/docker/dockerfile.service .
          docker push thoughts/thoughts-api:latest
          echo "Docker images pushed to Docker Hub"

      - name: Create PersistentVolume and PersistentVolumeClaim
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: postgres-pv
          spec:
            capacity:
              storage: 5Gi
            accessModes:
              - ReadWriteOnce
            hostPath:
              path: "/path/on/host"
          ---
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: postgres-pvc
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
          EOF

      - name: Pull Docker Images from Docker Hub
        run: docker pull thoughts/thoughts-api:latest

      - name: Set up kind
        run: |
          docker pull kindest/node:v1.27.3
          kind create cluster --name kind-cluster --image kindest/node:v1.27.3 --config operations/k8s/dev/kind-config.yaml

      - name: Load Docker Images into kind
        run: kind load docker-image thoughts/thoughts-api:latest --name kind-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f operations/k8s/dev/database
          kubectl apply -f operations/k8s/dev/thoughts
          kubectl wait pods --namespace=thoughts-system --selector app=thoughts --timeout=120s --for=condition=Ready

      - name: Wait for PostgreSQL to be Ready
        run: |
          sleep 30
          kubectl wait --for=condition=Ready pod -l app=database --timeout=120s --namespace=thoughts-system

      - name: Display Cluster Information
        run: |
          kubectl get nodes -o wide
          kubectl get svc -o wide
          kubectl get pods -o wide --watch --namespace=thoughts-system

      - name: Test Deployment
        run: |
          # Add your test commands here, such as curl or other API tests
          curl -il http://localhost:3000/v1/readiness
