name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build \
          -f operations/docker/dockerfile.service \
          -t ${{ secrets.DOCKER_USERNAME }}/service/thoughts-api:${{ github.sha }} \
          --build-arg BUILD_REF=$(VERSION) \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          .
        docker push ${{ secrets.DOCKER_USERNAME }}/service/thoughts-api:${{ github.sha }}

    - name: Set up kind cluster
      run: |
        kind create cluster --name your-cluster-name --config operations/k8s/dev/kind-config.yaml
        kubectl wait --timeout=120s --namespace=local-path-storage --for=condition=Available deployment/local-path-provisioner

    - name: Load Docker images
      run: kind load docker-image ${{ secrets.DOCKER_USERNAME }}/service/thoughts-api:${{ github.sha }} --name your-cluster-name

    - name: Apply Kubernetes manifests
      run: |
        kustomize build operations/k8s/dev/database | kubectl apply -f -
        kubectl rollout status --namespace=thoughts-system --watch --timeout=120s sts/database
        kustomize build operations/k8s/dev/thoughts | kubectl apply -f -
        kubectl wait pods --namespace=thoughts-system --selector app=thoughts --timeout=120s --for=condition=Ready

    - name: Restart deployment
      run: kubectl rollout restart deployment thoughts --namespace=thoughts-system
